config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :skills, only: %i[index show] do
    resources :levels, only: %i[update]
  end
  resources :users, only: %i[show] do
    post :update_skills, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/level.rb
class Level < ApplicationRecord
  belongs_to :skill

  validates :name, presence: true
  validates :exercise, presence: true, uniqueness: true

  after_save :update_skill_progression, if: :saved_change_to_completed?

  private

  def update_skill_progression
    skill.update_progression
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :levels
  has_many :user_skills
  has_many :users, through: :user_skills

  validates :name, presence: true, uniqueness: true, inclusion: { in: %w[Push-up Pull-up Split l-sit Squat Handstand] }
  validates :description, presence: true, uniqueness: true
  validates :progression, presence: true

  def update_progression
    total_levels = levels.count
    completed_levels = levels.where(completed: true).count
    progression = (completed_levels.to_f / total_levels * 100).round
    update(progression: progression)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_picture

  has_many :user_skills
  has_many :skills, through: :user_skills

  after_create :schedule_daily_reminder

  private

  def schedule_daily_reminder
    ReminderWorker.perform_in(24.hours, self.id)
  end
end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
  belongs_to :user
  belongs_to :skill
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  before_action :set_level, only: [:update]

  def index
    @levels = Level.all
  end

  def update
    if @level.update(level_params)
      @level.skill.update_progression
      render json: { success: true }
    else
      render json: { success: false, errors: @level.errors.full_messages }
    end
  end

  private

  def set_level
    @level = Level.find(params[:id])
  end

  def level_params
    params.require(:level).permit(:name, :exercise, :completed, :skill_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :authenticate_user!

  def index
    @all_skills = Skill.all
    @selected_skills = current_user.skills
    @selected_skill_ids = @selected_skills.pluck(:id)
  end

  def show
    @skill = Skill.find(params[:id])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: %i[username profile_picture])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authenticate_user!

  def index
    @user = current_user
  end

  def show
    @user = current_user
  end

  def update_skills
    current_user.skill_ids = params[:skill_ids]
    if current_user.save
      head :ok
    else
      head :unprocessable_entity
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LevelUp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="homepage">
  <div class="title">
    <h1>LEVEL UP</h1>
    <h3>GAINING NEW SKILLS HAS NEVER BEEN EASIER</h3>
  </div>
  <div class="button button-container">
    <%= link_to skills_path do %>
      <button class ="btn large">ENTER</button>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
   <div class="container-fluid">
     <%= link_to skills_path, class: "navbar-brand" do %>
        <h3>LEVEL UP</h3>
     <% end %>

     <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
       <% if user_signed_in? && current_user.profile_picture.attached? %>
        <%= image_tag current_user.profile_picture, class: "avatar", alt: "dropdown menu" %>
      <% else %>
        <%= image_tag("homepage.webp", class: "avatar", alt: "dropdown menu") %>
      <% end %>
     </button>

     <div class="collapse navbar-collapse" id="navbarSupportedContent">
       <ul class="navbar-nav me-auto">
         <% if user_signed_in? %>
           <li class="nav-item active">
             <%= link_to "Profile", user_path(current_user), class: "nav-link" %>
           </li>
           <li class="nav-item">
             <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
           </li>
         <% else %>
           <li class="nav-item">
             <%= link_to "Login", new_user_session_path, class: "nav-link" %>
           </li>
         <% end %>
       </ul>
     </div>
   </div>
 </div>

app/views/skills/index.html.erb
<div class="container" data-controller="skills" data-skills-user-id="<%= current_user.id %>" data-selected-skill-ids="<%= @selected_skill_ids.to_json %>">
  <br>
  <div class="dropdown">
  <button class="btn large btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
    💪
  </button>
  <ul class="dropdown-menu">
    <% @all_skills.each do |skill| %>
      <li>
        <a class="dropdown-item" href="#" data-action="click->skills#toggleSkill" data-skill-id="<%= skill.id %>">
          <%= skill.name %>
        </a>
      </li>
    <% end %>
  </ul>
</div>
  <div class="cards">
    <% @selected_skills.each do |skill| %>
      <%= link_to skill_path(skill) do %>
        <div class="card">
          <%= image_tag "#{skill.name}.webp", class: "card-img", alt: "Card image #{skill.name}" %>
          <div class="card-body">
            <h4 class="card-title"><%= skill.name %></h4>
            <div class="progress" role="progressbar" aria-label="Example with label" aria-valuenow="<%= skill.progression %>" aria-valuemin="0" aria-valuemax="100">
              <% if skill.progression < 100 %>
                <div class="progress-bar bg-danger" style="width: <%= skill.progression %>%"><%= skill.progression %>%</div>
              <% else %>
                <div class="progress-full"><p>You have mastered this skill 💪</p></div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/skills/show.html.erb
<div class="container" data-controller="levels" data-levels-skill-id-value="<%= @skill.id %>">
  <h1><%= @skill.name %></h1>
  <br>
  <p><%= @skill.description.lines('.').first %></p>
  <p><%= @skill.description.lines('.').second %></p>
  <p><%= @skill.description.lines('.').third %></p>
  <% @skill.levels.each_with_index do |level, index| %>
    <h5><%= "##{index + 1} - #{level.name}" %></h5>
    <p><%= level.exercise.split('. ')[0...-1].join('. ') + '.' %></p>
    <div class="card-status">
      <p><%= level.exercise.lines('.').last %></p>
      <%= form_with model: @level, local: false do |form| %>
        <%= form.check_box :completed, checked: level.completed, data: { action: 'change->levels#toggle', levels_level_id_value: level.id } %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="profile">
    <div class="profile-pic-area mt-4">
      <% if @user.profile_picture.attached? %>
        <%= image_tag @user.profile_picture, class: "avatar-large" %>
      <% else %>
        <%= image_tag("homepage.webp", class: "avatar-large") %>
      <% end %>
    </div>
    <div data-controller="toggle" class="mt-5">
      <div class="info">
        <div class="info details">
          <p><strong>Username</strong></p>
          <p><%= @user.username %></p>
        </div>
        <div class="info details">
          <p><strong>Email</strong></p>
          <p><%= @user.email %></p>
        </div>
        <div class="info details">
          <p><strong>Password</strong></p>
          <p>**********</p>
        </div>
        <br>
        <div class="edit">
          <p><strong>Edit</strong></p>
          <%= link_to edit_user_registration_path do %>
            <button class="btn profile-edit"><i class="fa-solid fa-pen-to-square"></i></button>
          <% end %>
        </div>
        <hr>
        <div class="delete">
          <p><strong>Delete account</strong></p>
          <%= link_to edit_user_registration_path do %>
            <button class="btn red"><i class="fa-solid fa-user-xmark"></i></button>
          <% end %>
        </div>
      </div>
      <div class="logout-btn button-container">
        <%= link_to edit_user_registration_path do %>
          <button class="btn large">LOG OUT</button>
        <% end %>
      </div>
    </div>
  </div>
</div>